### ISSUE TITLE
Todo-List

### ISSUE THREAD

**Issue by lucasliebe** [jannis-baum/adblock-plus-plus#1]
- [ ] use google news for similarities and clean database
- [ ] using summaries for similarity
- [ ] Check/ Make more reliable on multiple sites
- [ ] Try to use NonSql DB and compare
- [ ] include OpenAI into sentence generation
- [ ] maybe pre generate sentences?

**Comment by jannis-baum** [comment]
- [ ] use venvs
- [ ] setup everything to be tried out easily
